//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _22_EntityFramework_DBFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class BASE_MESSAGE_RECENT
    {
        public string ID { get; set; }
        public string USER_ID { get; set; }
        public string TARGET_CATEGORY { get; set; }
        public string TARGET_ID { get; set; }
        public string REAL_NAME { get; set; }
        public string COMPANY_NAME { get; set; }
        public string DEPARTMENT_NAME { get; set; }
        public Nullable<System.DateTime> MODIFIED_ON { get; set; }
    }
}
