//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _22_EntityFramework_DBFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Base_Log
    {
        public string ID { get; set; }
        public string TASK_ID { get; set; }
        public string SERVICE { get; set; }
        public string USER_ID { get; set; }
        public string USER_REAL_NAME { get; set; }
        public string PARAMETERS { get; set; }
        public string URL_REFERRER { get; set; }
        public string CLIENT_IP { get; set; }
        public string SERVER_IP { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<int> ELAPSED_TICKS { get; set; }
        public string COMPANY_ID { get; set; }
        public string IPADDRESS { get; set; }
        public string Category_Code { get; set; }
        public string Category { get; set; }
        public Nullable<short> State_Code { get; set; }
        public string State { get; set; }
        public Nullable<int> Sort_Code { get; set; }
        public Nullable<short> Allow_Edit { get; set; }
        public Nullable<short> Allow_Delete { get; set; }
        public Nullable<short> Is_Visible { get; set; }
        public Nullable<short> Is_Public { get; set; }
        public Nullable<short> Enabled { get; set; }
        public Nullable<short> Deletion_State_Code { get; set; }
        public Nullable<System.DateTime> CREATE_ON { get; set; }
        public Nullable<System.DateTime> MODIFIED_ON { get; set; }
        public string WEB_URL { get; set; }
        public string COMPANY { get; set; }
        public string CREATE_USER_ID { get; set; }
        public string CREATE_BY { get; set; }
        public string MODIFIED_USER_ID { get; set; }
        public string MODIFIED_BY { get; set; }
    }
}
