//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _22_EntityFramework_DBFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Base_Department
    {
        public string ID { get; set; }
        public string PARENT_ID { get; set; }
        public string PARENT_NAME { get; set; }
        public string PARENT_CODE { get; set; }
        public string COMPANY_ID { get; set; }
        public string COMPANY_NAME { get; set; }
        public string COMPANY_CODE { get; set; }
        public string MANAGER_ID { get; set; }
        public string MANAGER { get; set; }
        public string MANAGER_MOBILE { get; set; }
        public string MANAGER_QQ { get; set; }
        public string CODE { get; set; }
        public string SHORT_NAME { get; set; }
        public string FULL_NAME { get; set; }
        public string CATEGORY_CODE { get; set; }
        public string CATEGORY_NAME { get; set; }
        public string OUTER_PHONE { get; set; }
        public string INNER_PHONE { get; set; }
        public string FAX { get; set; }
        public Nullable<int> DELETION_STATE_CODE { get; set; }
        public Nullable<int> ENABLED { get; set; }
        public Nullable<int> SORT_CODE { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<System.DateTime> CREATE_ON { get; set; }
        public string CREATE_USER_ID { get; set; }
        public string CREATE_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_ON { get; set; }
        public string MODIFIED_USER_ID { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<int> IS_VISIBLE { get; set; }
    }
}
