//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _22_EntityFramework_DBFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Base_Contact
    {
        public string Id { get; set; }
        public string Parent_Id { get; set; }
        public string Title { get; set; }
        public string Color { get; set; }
        public string Style { get; set; }
        public string Contents { get; set; }
        public string Priority { get; set; }
        public string Customer_Name { get; set; }
        public string Customer_Sex { get; set; }
        public string Customer_Telephone { get; set; }
        public string Customer_Email { get; set; }
        public Nullable<int> Cancel_Top_Day { get; set; }
        public string Source { get; set; }
        public string Category_Code { get; set; }
        public string Label_Mark { get; set; }
        public string Description { get; set; }
        public Nullable<int> Send_Count { get; set; }
        public Nullable<int> Read_Count { get; set; }
        public Nullable<int> Reply_Count { get; set; }
        public Nullable<int> Must_Read { get; set; }
        public Nullable<int> Must_Reply { get; set; }
        public Nullable<int> Is_Open { get; set; }
        public string IPAddress { get; set; }
        public Nullable<int> Allow_Comments { get; set; }
        public Nullable<int> Enabled { get; set; }
        public string Comment_User_Id { get; set; }
        public string Comment_User_Real_Name { get; set; }
        public Nullable<System.DateTime> Comment_Date { get; set; }
        public Nullable<int> Deletion_State_Code { get; set; }
        public string Audit_Status { get; set; }
        public string Audit_User_Id { get; set; }
        public string Audit_User_Real_Name { get; set; }
        public Nullable<int> Sort_Code { get; set; }
        public Nullable<System.DateTime> Create_On { get; set; }
        public string Create_User_Id { get; set; }
        public string Create_By { get; set; }
        public string Create_Department_Id { get; set; }
        public string Create_Department { get; set; }
        public string Create_Company { get; set; }
        public string Create_Company_Id { get; set; }
        public Nullable<System.DateTime> Modified_On { get; set; }
        public string Modified_User_Id { get; set; }
        public string Modified_By { get; set; }
        public string Recruit_Num { get; set; }
    }
}
