//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _22_EntityFramework_DBFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class BASE_ORGANIZE_HORIZONTAL
    {
        public string ID { get; set; }
        public string CODE { get; set; }
        public string FULL_NAME { get; set; }
        public string HEADQUARTERS_ID { get; set; }
        public string HEADQUARTERS_CODE { get; set; }
        public string HEADQUARTERS { get; set; }
        public string BIG_AREA_CODE { get; set; }
        public string BIG_AREA { get; set; }
        public string AREA_CODE { get; set; }
        public string AREA { get; set; }
        public string TRANSFER_FIRST_ID { get; set; }
        public string TRANSFER_FIRST_CODE { get; set; }
        public string TRANSFER_FIRST { get; set; }
        public string COMPANY_FIRST_ID { get; set; }
        public string COMPANY_FIRST_CODE { get; set; }
        public string COMPANY_FIRST { get; set; }
        public string COMPANY_SECOND_ID { get; set; }
        public string COMPANY_SECOND_CODE { get; set; }
        public string COMPANY_SECOND { get; set; }
        public string CONTRACT_ID { get; set; }
        public string CONTRACT_CODE { get; set; }
        public string CONTRACT { get; set; }
        public string PARENT_ID { get; set; }
        public string PARENT_NAME { get; set; }
        public string PARENT_CODE { get; set; }
        public string COUNTRY_ID { get; set; }
        public string COUNTRY_CODE { get; set; }
        public string COUNTRY { get; set; }
        public string PROVINCE_ID { get; set; }
        public string PROVINCE_CODE { get; set; }
        public string PROVINCE { get; set; }
        public string CITY_ID { get; set; }
        public string CITY_CODE { get; set; }
        public string CITY { get; set; }
        public string DISTRICT_ID { get; set; }
        public string DISTRICT_CODE { get; set; }
        public string DISTRICT { get; set; }
        public string STREET_ID { get; set; }
        public string STREET_CODE { get; set; }
        public string STREET { get; set; }
        public Nullable<System.DateTime> CREATE_ON { get; set; }
        public string CREATE_USER_ID { get; set; }
        public string CREATE_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_ON { get; set; }
        public string MODIFIED_USER_ID { get; set; }
        public string MODIFIED_BY { get; set; }
        public string CATEGORY { get; set; }
    }
}
