//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _22_EntityFramework_DBFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Base_User_Address
    {
        public string ID { get; set; }
        public string USER_ID { get; set; }
        public string REAL_NAME { get; set; }
        public string PROVINCE_ID { get; set; }
        public string PROVINCE { get; set; }
        public string CITY_ID { get; set; }
        public string CITY { get; set; }
        public string DISTRICT_ID { get; set; }
        public string DISTRICT { get; set; }
        public string ADDRESS { get; set; }
        public string POST_CODE { get; set; }
        public string PHONE { get; set; }
        public string FAX { get; set; }
        public string MOBILE { get; set; }
        public string EMAIL { get; set; }
        public string DELIVER_CATEGORY { get; set; }
        public Nullable<int> SORT_CODE { get; set; }
        public Nullable<int> DELETION_STATE_CODE { get; set; }
        public Nullable<int> ENABLED { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<System.DateTime> CREATE_ON { get; set; }
        public string CREATE_USER_ID { get; set; }
        public string CREATE_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_ON { get; set; }
        public string MODIFIED_USER_ID { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<int> CATEGORY_CODE { get; set; }
        public Nullable<int> DEFAULT_ADDRESS { get; set; }
        public string EMPLOYEE_CODE { get; set; }
        public string EMPLOYEE_ID { get; set; }
        public string COMPANY_CODE { get; set; }
        public string COMPANY_ID { get; set; }
        public string BOX_CODE { get; set; }
        public string STREET { get; set; }
        public string STREET_ID { get; set; }
    }
}
