//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _22_EntityFramework_DBFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Base_User
    {
        public string Id { get; set; }
        public string Code { get; set; }
        public string User_Name { get; set; }
        public string Real_Name { get; set; }
        public string NickName { get; set; }
        public string Quick_Query { get; set; }
        public string Simple_Spelling { get; set; }
        public string Duty { get; set; }
        public string Title { get; set; }
        public string Gender { get; set; }
        public string Signature { get; set; }
        public string IDCard { get; set; }
        public string Birthday { get; set; }
        public string Company_Id { get; set; }
        public string Company_Name { get; set; }
        public string Company_Code { get; set; }
        public string Department_Id { get; set; }
        public string Department_Name { get; set; }
        public string Department_Code { get; set; }
        public string Sub_Company_Id { get; set; }
        public string Sub_Company_Name { get; set; }
        public string Sub_Department_Id { get; set; }
        public string Sub_Department_Name { get; set; }
        public string Workgroup_Id { get; set; }
        public string Workgroup_Name { get; set; }
        public Nullable<int> Province_Id { get; set; }
        public string Province { get; set; }
        public Nullable<int> City_Id { get; set; }
        public string City { get; set; }
        public Nullable<int> District_Id { get; set; }
        public string District { get; set; }
        public string Home_Address { get; set; }
        public string Description { get; set; }
        public Nullable<short> Is_Administrator { get; set; }
        public string Work_Category { get; set; }
        public Nullable<int> Security_Level { get; set; }
        public string Lang { get; set; }
        public string Theme { get; set; }
        public Nullable<int> Score { get; set; }
        public Nullable<int> Fans { get; set; }
        public string User_From { get; set; }
        public string Manager_Id { get; set; }
        public string Manager { get; set; }
        public Nullable<short> MANAGER_AUDIT_STATUS { get; set; }
        public Nullable<System.DateTime> MANAGER_AUDIT_DATE { get; set; }
        public Nullable<int> Sort_Code { get; set; }
        public Nullable<short> Is_Staff { get; set; }
        public Nullable<short> Is_Visible { get; set; }
        public Nullable<short> Enabled { get; set; }
        public Nullable<short> Deletion_State_Code { get; set; }
        public string Audit_Status { get; set; }
        public Nullable<System.DateTime> Create_On { get; set; }
        public string Create_User_Id { get; set; }
        public string Create_User_Code { get; set; }
        public string Create_By { get; set; }
        public Nullable<System.DateTime> Modified_On { get; set; }
        public string Modified_User_Id { get; set; }
        public string Modified_By { get; set; }
    }
}
