//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _22_EntityFramework_DBFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Base_Organize_Log
    {
        public string Id { get; set; }
        public string Table_Code { get; set; }
        public string Table_Description { get; set; }
        public string Record_Key { get; set; }
        public string Column_Code { get; set; }
        public string Column_Description { get; set; }
        public string Old_Key { get; set; }
        public string Old_Value { get; set; }
        public string New_Key { get; set; }
        public string New_Value { get; set; }
        public string Create_IP { get; set; }
        public Nullable<System.DateTime> Create_On { get; set; }
        public string Create_Company_Id { get; set; }
        public string Create_Company_Code { get; set; }
        public string Create_Company { get; set; }
        public string Create_User_Id { get; set; }
        public string Create_User_Code { get; set; }
        public string Create_By { get; set; }
        public string Data_From { get; set; }
    }
}
