//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _22_EntityFramework_DBFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Base_User_Contact
    {
        public string Id { get; set; }
        public string Email { get; set; }
        public int Email_Valiated { get; set; }
        public string Mobile { get; set; }
        public Nullable<int> Mobile_Valiated { get; set; }
        public Nullable<System.DateTime> Mobile_Verification_Date { get; set; }
        public Nullable<int> Mobile_Unique { get; set; }
        public Nullable<short> Show_Mobile { get; set; }
        public string Telephone { get; set; }
        public string QQ { get; set; }
        public string WW { get; set; }
        public string WeChat_Open_Id { get; set; }
        public string WeChat { get; set; }
        public int WeChat_Valiated { get; set; }
        public string YiXin { get; set; }
        public int YiXin_Valiated { get; set; }
        public string Short_Number { get; set; }
        public string Extension { get; set; }
        public string YY { get; set; }
        public string Company_Mail { get; set; }
        public string Emergency_Contact { get; set; }
        public Nullable<System.DateTime> Create_On { get; set; }
        public string Create_User_Id { get; set; }
        public string Create_By { get; set; }
        public Nullable<System.DateTime> Modified_On { get; set; }
        public string Modified_User_Id { get; set; }
        public string Modified_By { get; set; }
        public string Company_Id { get; set; }
    }
}
