//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _22_EntityFramework_DBFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Base_Login_Log
    {
        public string Id { get; set; }
        public System.DateTime Create_On { get; set; }
        public string User_Name { get; set; }
        public string Login_Status { get; set; }
        public string IPAddress { get; set; }
        public string IPAddress_Name { get; set; }
        public string MAC_Address { get; set; }
        public string System_Code { get; set; }
        public string User_Id { get; set; }
        public string Real_Name { get; set; }
        public string Company_Id { get; set; }
        public string Company_Code { get; set; }
        public string Company_Name { get; set; }
        public Nullable<short> Log_Level { get; set; }
        public string Source_Type { get; set; }
        public string Province { get; set; }
        public string City { get; set; }
        public string Service { get; set; }
        public Nullable<int> ElapsedTicks { get; set; }
        public string Target_Application { get; set; }
        public string Target_Ip { get; set; }
        public Nullable<short> Result { get; set; }
        public Nullable<short> Operation_Type { get; set; }
    }
}
