//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _22_EntityFramework_DBFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Base_Module
    {
        public string Id { get; set; }
        public string Parent_Id { get; set; }
        public string Code { get; set; }
        public string Full_Name { get; set; }
        public string Category_Code { get; set; }
        public string Imag_Url { get; set; }
        public string Image_Index { get; set; }
        public string Selected_Image_Index { get; set; }
        public string Navigate_Url { get; set; }
        public string Target { get; set; }
        public string Web_Browser { get; set; }
        public string Form_Name { get; set; }
        public string Assembly_Name { get; set; }
        public string Permission_Scope_Tables { get; set; }
        public Nullable<short> Is_Menu { get; set; }
        public short Is_Public { get; set; }
        public short Is_Scope { get; set; }
        public short Is_Visible { get; set; }
        public Nullable<System.DateTime> Last_Call { get; set; }
        public Nullable<int> Sort_Code { get; set; }
        public Nullable<short> Enabled { get; set; }
        public short Deletion_State_Code { get; set; }
        public short Expand { get; set; }
        public short Allow_Edit { get; set; }
        public short Allow_Delete { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> Create_On { get; set; }
        public string Create_User_Id { get; set; }
        public string Create_By { get; set; }
        public Nullable<System.DateTime> Modified_On { get; set; }
        public string Modified_User_Id { get; set; }
        public string Modified_By { get; set; }
        public Nullable<int> Authorized_Days { get; set; }
        public Nullable<int> Security_Level { get; set; }
    }
}
