//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _22_EntityFramework_DBFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Base_Organize
    {
        public string Id { get; set; }
        public string Code { get; set; }
        public string Short_Name { get; set; }
        public string Full_Name { get; set; }
        public string Standard_Name { get; set; }
        public string Standard_Code { get; set; }
        public string Parent_Id { get; set; }
        public string Parent_Name { get; set; }
        public string Parent_Code { get; set; }
        public Nullable<int> Sort_Code { get; set; }
        public string Category_Code { get; set; }
        public Nullable<int> Layer { get; set; }
        public string Outer_Phone { get; set; }
        public string Inner_Phone { get; set; }
        public string Fax { get; set; }
        public string Postal_Code { get; set; }
        public string Web { get; set; }
        public Nullable<short> Is_Inner_Organize { get; set; }
        public string Bank { get; set; }
        public string Bank_Account { get; set; }
        public string Description { get; set; }
        public string Big_Area { get; set; }
        public string Area { get; set; }
        public string Joining_Methods { get; set; }
        public Nullable<short> Contain_Child_Nodes { get; set; }
        public string Quick_Query { get; set; }
        public string Simple_Spelling { get; set; }
        public Nullable<int> Province_Id { get; set; }
        public string Province { get; set; }
        public Nullable<int> City_Id { get; set; }
        public string City { get; set; }
        public Nullable<int> District_Id { get; set; }
        public string District { get; set; }
        public Nullable<int> Street_Id { get; set; }
        public string Street { get; set; }
        public string Address { get; set; }
        public string Statistical_Name { get; set; }
        public string Master_Id { get; set; }
        public string Master { get; set; }
        public string Master_Phone { get; set; }
        public string Master_Mobile { get; set; }
        public string Master_QQ { get; set; }
        public string Emergency_Call { get; set; }
        public string Business_Phone { get; set; }
        public string Manage_Id { get; set; }
        public string Manage_Name { get; set; }
        public string Manager_Phone { get; set; }
        public string Manager { get; set; }
        public string Manager_Mobile { get; set; }
        public string Manager_QQ { get; set; }
        public string Service_Manager_Id { get; set; }
        public string Service_Manager { get; set; }
        public string Service_Manager_QQ { get; set; }
        public string Service_Manager_Phone { get; set; }
        public string Service_Manager_Mobile { get; set; }
        public string Complaint_Phone { get; set; }
        public Nullable<short> Deletion_State_Code { get; set; }
        public Nullable<short> Enabled { get; set; }
        public Nullable<System.DateTime> Create_On { get; set; }
        public string Create_User_Id { get; set; }
        public string Create_By { get; set; }
        public Nullable<System.DateTime> Modified_On { get; set; }
        public string Modified_User_Id { get; set; }
        public string Modified_By { get; set; }
        public string Site_Telephone { get; set; }
        public Nullable<short> Web_Enabled { get; set; }
        public Nullable<int> Country_Id { get; set; }
        public string Country { get; set; }
        public string Organize_From { get; set; }
        public string Audit_Status { get; set; }
        public string English_Name { get; set; }
    }
}
