//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _22_EntityFramework_DBFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Base_Exception
    {
        public string ID { get; set; }
        public string SYSTEM_CODE { get; set; }
        public Nullable<int> EVENT_ID { get; set; }
        public string CATEGORY { get; set; }
        public Nullable<int> PRIORITY { get; set; }
        public string SEVERITY { get; set; }
        public string IPADDRESS { get; set; }
        public string TITLE { get; set; }
        public Nullable<System.DateTime> TIMESTAMP { get; set; }
        public string MACHINE_NAME { get; set; }
        public string APPDOMAIN_NAME { get; set; }
        public string PROCESS_ID { get; set; }
        public string PROCESS_NAME { get; set; }
        public string THREAD_NAME { get; set; }
        public string WIN32_THREAD_ID { get; set; }
        public string MESSAGE { get; set; }
        public string FORMATTED_MESSAGE { get; set; }
        public Nullable<System.DateTime> CREATE_ON { get; set; }
        public string CREATE_USER_ID { get; set; }
        public string CREATE_BY { get; set; }
    }
}
