//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _22_EntityFramework_DBFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Base_News
    {
        public string ID { get; set; }
        public string FOLDER_ID { get; set; }
        public string COMPANY_ID { get; set; }
        public string COMPANY_NAME { get; set; }
        public string DEPARTMENT_ID { get; set; }
        public string DEPARTMENT_NAME { get; set; }
        public string CATEGORY_CODE { get; set; }
        public string CODE { get; set; }
        public string TITLE { get; set; }
        public string FILE_PATH { get; set; }
        public string INTRODUCTION { get; set; }
        public string CONTENTS { get; set; }
        public string SOURCE { get; set; }
        public string KEYWORDS { get; set; }
        public Nullable<int> FILE_SIZE { get; set; }
        public string IMAGE_URL { get; set; }
        public Nullable<int> HOME_PAGE { get; set; }
        public Nullable<int> SUB_PAGE { get; set; }
        public string AUDIT_STATUS { get; set; }
        public Nullable<int> READ_COUNT { get; set; }
        public Nullable<int> DELETION_STATE_CODE { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<int> ENABLED { get; set; }
        public Nullable<int> SORT_CODE { get; set; }
        public Nullable<System.DateTime> CREATE_ON { get; set; }
        public string CREATE_BY { get; set; }
        public string CREATE_USER_ID { get; set; }
        public Nullable<System.DateTime> MODIFIED_ON { get; set; }
        public string MODIFIED_BY { get; set; }
        public string MODIFIED_USER_ID { get; set; }
    }
}
