//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _22_EntityFramework_DBFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Base_User_Express
    {
        public string ID { get; set; }
        public Nullable<int> IS_CHECK_BALANCE { get; set; }
        public Nullable<double> TRANSFER_ADD_FEE { get; set; }
        public string OWNER_ID { get; set; }
        public string OWNER_RANGE { get; set; }
        public Nullable<double> DISPATCH_ADD_FEE { get; set; }
        public string RECEIVE_AREA { get; set; }
        public string MODIFIED_USER_ID { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_ON { get; set; }
        public string CREATE_USER_ID { get; set; }
        public string CREATE_BY { get; set; }
        public Nullable<System.DateTime> CREATE_ON { get; set; }
        public Nullable<int> WEB_ENABLED { get; set; }
        public string DISP_AREA { get; set; }
        public string LONGITUDE { get; set; }
        public string LATITUDE { get; set; }
        public string SAN_DUAN_MA { get; set; }
        public Nullable<int> IS_RECEIVE { get; set; }
        public Nullable<int> IS_DISP { get; set; }
        public string COMPANY_ID { get; set; }
        public Nullable<int> NETWORK_ORDERS { get; set; }
        public string ORDER_ASSIGN_TO { get; set; }
        public string COOPERATE_FUNCTION { get; set; }
        public Nullable<decimal> SYS_STSBDKW3OZ1775BWH74P2XAKHX { get; set; }
        public Nullable<decimal> SYS_STSIF_NCZXZZ98_YLI21T6PG2G { get; set; }
    }
}
