//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _22_EntityFramework_DBFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Base_Message
    {
        public string ID { get; set; }
        public string PARENT_ID { get; set; }
        public string RECEIVER_DEPARTMENT_ID { get; set; }
        public string RECEIVER_DEPARTMENT_NAME { get; set; }
        public string RECEIVER_ID { get; set; }
        public string RECEIVER_REAL_NAME { get; set; }
        public string CATEGORY_CODE { get; set; }
        public string FUNCTION_CODE { get; set; }
        public string OBJECT_ID { get; set; }
        public string TITLE { get; set; }
        public string CONTENTS { get; set; }
        public Nullable<int> IS_NEW { get; set; }
        public int READ_COUNT { get; set; }
        public Nullable<System.DateTime> READ_DATE { get; set; }
        public string TARGET_URL { get; set; }
        public string IPADDRESS { get; set; }
        public string QQ { get; set; }
        public string EMAIL { get; set; }
        public string TELEPHONE { get; set; }
        public string CREATE_DEPARTMENT_ID { get; set; }
        public string CREATE_DEPARTMENT_NAME { get; set; }
        public Nullable<int> DELETION_STATE_CODE { get; set; }
        public int ENABLED { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<int> SORT_CODE { get; set; }
        public Nullable<System.DateTime> CREATE_ON { get; set; }
        public string CREATE_USER_ID { get; set; }
        public string CREATE_BY { get; set; }
        public string MODIFIED_BY { get; set; }
        public string MODIFIED_USER_ID { get; set; }
        public Nullable<System.DateTime> MODIFIED_ON { get; set; }
        public string CREATE_COMPANY_ID { get; set; }
        public string CREATE_COMPANY_NAME { get; set; }
    }
}
