//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _22_EntityFramework_DBFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Base_Folder
    {
        public string ID { get; set; }
        public string PARENT_ID { get; set; }
        public string FOLDER_NAME { get; set; }
        public string STATE_CODE { get; set; }
        public int SORT_CODE { get; set; }
        public int ALLOW_EDIT { get; set; }
        public int ALLOW_DELETE { get; set; }
        public int IS_PUBLIC { get; set; }
        public int ENABLED { get; set; }
        public int DELETION_STATE_CODE { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<System.DateTime> CREATE_ON { get; set; }
        public string CREATE_USER_ID { get; set; }
        public string CREATE_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_ON { get; set; }
        public string MODIFIED_USER_ID { get; set; }
        public string MODIFIED_BY { get; set; }
    }
}
