//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _22_EntityFramework_DBFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Base_Staff
    {
        public string ID { get; set; }
        public string USER_ID { get; set; }
        public string USER_NAME { get; set; }
        public string REAL_NAME { get; set; }
        public string CODE { get; set; }
        public string GENDER { get; set; }
        public string COMPANY_ID { get; set; }
        public string SUB_COMPANY_ID { get; set; }
        public string DEPARTMENT_ID { get; set; }
        public string WORKGROUP_ID { get; set; }
        public string QUICK_QUERY { get; set; }
        public string DUTY_ID { get; set; }
        public string DUTY_CODE { get; set; }
        public string DUTY_TYPE { get; set; }
        public string DUTY_LEVEL { get; set; }
        public string DUTY { get; set; }
        public string IDENTIFICATION_CODE { get; set; }
        public string ID_CARD { get; set; }
        public string BANK_CODE { get; set; }
        public string REWAR_CARD { get; set; }
        public string MEDICAL_CARD { get; set; }
        public string UNION_MEMBER { get; set; }
        public string EMAIL { get; set; }
        public string MOBILE { get; set; }
        public string SHORT_NUMBER { get; set; }
        public string TELEPHONE { get; set; }
        public string QQ { get; set; }
        public string OFFICE_PHONE { get; set; }
        public string OFFICE_POSTCODE { get; set; }
        public string OFFICE_ADDRESS { get; set; }
        public string OFFICE_FAX { get; set; }
        public string AGE { get; set; }
        public string BIRTHDAY { get; set; }
        public string HEIGHT { get; set; }
        public string WEIGHT { get; set; }
        public string EDUCATION { get; set; }
        public string SCHOOL { get; set; }
        public string GRADUATION_DATE { get; set; }
        public string MAJOR { get; set; }
        public string DEGREE { get; set; }
        public string TITLE_ID { get; set; }
        public string TITLE_DATE { get; set; }
        public string TITLE_LEVEL { get; set; }
        public string TITLE { get; set; }
        public string WORKING_DATE { get; set; }
        public string JOIN_IN_DATE { get; set; }
        public string HOME_POST_CODE { get; set; }
        public string HOME_ADDRESS { get; set; }
        public string HOME_PHONE { get; set; }
        public string HOME_FAX { get; set; }
        public string PROVINCE { get; set; }
        public string CAR_CODE { get; set; }
        public string CITY { get; set; }
        public string AREA { get; set; }
        public string NATIVE_PLACE { get; set; }
        public string PARTY { get; set; }
        public string NATION { get; set; }
        public string NATIONALITY { get; set; }
        public string WORKING_PROPERTY { get; set; }
        public string COMPETENCY { get; set; }
        public string EMERGENCY_CONTACT { get; set; }
        public Nullable<System.DateTime> WEDDING_DAY { get; set; }
        public Nullable<System.DateTime> DIVORCE { get; set; }
        public Nullable<System.DateTime> CHILD_BIRTHDAY1 { get; set; }
        public Nullable<System.DateTime> CHILD_BIRTHDAY2 { get; set; }
        public Nullable<int> IS_DIMISSION { get; set; }
        public string DIMISSION_DATE { get; set; }
        public string DIMISSION_CAUSE { get; set; }
        public string DIMISSION_WHITHER { get; set; }
        public Nullable<int> ENABLED { get; set; }
        public Nullable<int> DELETION_STATE_CODE { get; set; }
        public Nullable<int> SORT_CODE { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<System.DateTime> CREATE_ON { get; set; }
        public string CREATE_USER_ID { get; set; }
        public string CREATE_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_ON { get; set; }
        public string MODIFIED_USER_ID { get; set; }
        public string MODIFIED_BY { get; set; }
        public string CURRENT_DISTRICT { get; set; }
        public string CURRENT_CITY { get; set; }
        public string CURRENT_PROVINCE { get; set; }
        public string DISTRICT { get; set; }
        public string COMPANY_NAME { get; set; }
        public string DEPARTMENT_NAME { get; set; }
        public string WORKGROUP_NAME { get; set; }
        public string MARRIAGE { get; set; }
        public string EXTENSION { get; set; }
        public string BANK_NAME { get; set; }
        public string BANK_USER_NAME { get; set; }
    }
}
