//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _22_EntityFramework_DBFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Business_Card
    {
        public string Id { get; set; }
        public string FullName { get; set; }
        public string Company_Name { get; set; }
        public string Title { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string Fax { get; set; }
        public string Big_Area { get; set; }
        public string Duty { get; set; }
        public string Responsibility { get; set; }
        public string Tranfer_Range { get; set; }
        public string Description { get; set; }
        public string Tranfer_Center { get; set; }
        public string Department_Name { get; set; }
        public string Department_Id { get; set; }
        public string Category_Code { get; set; }
        public string Postalcode { get; set; }
        public string Address { get; set; }
        public string OfficePhone { get; set; }
        public string QQ { get; set; }
        public string Web { get; set; }
        public string BankName { get; set; }
        public string BankAccount { get; set; }
        public string TaxAccount { get; set; }
        public Nullable<int> Personal { get; set; }
        public int Enabled { get; set; }
        public int Deletion_State_Code { get; set; }
        public Nullable<int> Sort_Code { get; set; }
        public System.DateTime Create_On { get; set; }
        public string Create_User_Id { get; set; }
        public string Create_By { get; set; }
        public Nullable<System.DateTime> Modified_On { get; set; }
        public string Modified_User_Id { get; set; }
        public string Modified_By { get; set; }
        public string Center_Name { get; set; }
        public string Center_Id { get; set; }
        public string Sub_Department_Name { get; set; }
        public string Sub_Department_Id { get; set; }
    }
}
