//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _22_EntityFramework_DBFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Colp_Diagnose_Detail
    {
        public string Id { get; set; }
        public string Parent_Id { get; set; }
        public string Parent_Name { get; set; }
        public string Parent_Code { get; set; }
        public string Organization_Id { get; set; }
        public string Organization_Name { get; set; }
        public string Organization_Code { get; set; }
        public string Department_Id { get; set; }
        public string Department_Name { get; set; }
        public string Department_Code { get; set; }
        public string Equipment_Id { get; set; }
        public string Equipment_Name { get; set; }
        public string Equipment_Code { get; set; }
        public string User_Id { get; set; }
        public string User_Name { get; set; }
        public string User_Code { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Patientsubject { get; set; }
        public Nullable<int> Sufficient { get; set; }
        public Nullable<int> OverallCervixVisible { get; set; }
        public Nullable<int> OverallSCJVisible { get; set; }
        public Nullable<int> BeforAcidErosion { get; set; }
        public Nullable<int> BeforAcidCrisp { get; set; }
        public Nullable<int> BeforAcidBlood { get; set; }
        public Nullable<int> BeforAcidInflammation { get; set; }
        public Nullable<int> BeforAcidWhite { get; set; }
        public Nullable<int> BeforAcidChange { get; set; }
        public Nullable<int> AfterAcidWhite { get; set; }
        public Nullable<int> AfterAcidInfection { get; set; }
        public Nullable<int> Referral { get; set; }
        public string ReferralCode { get; set; }
        public Nullable<int> NormalLepidoteEpidermisRipe { get; set; }
        public Nullable<int> NormalLepidoteEpidermisAtrophy { get; set; }
        public Nullable<int> NormalLepidoteEpidermisGestation { get; set; }
        public Nullable<int> NormalHistogramEpidermisShift { get; set; }
        public Nullable<int> NormalNabothCyst { get; set; }
        public Nullable<int> NormalBodyGlandOpening { get; set; }
        public Nullable<int> NormalVingerShrink { get; set; }
        public Nullable<int> NormalMetaplasticEpithelium { get; set; }
        public Nullable<int> LSILTranslucent { get; set; }
        public Nullable<int> LSILBoundaryVague { get; set; }
        public Nullable<int> LSILWartyBulge { get; set; }
        public Nullable<int> LSILFlatNipple { get; set; }
        public Nullable<int> LSILNone { get; set; }
        public Nullable<int> LSILPunctate { get; set; }
        public Nullable<int> LSILSmallInlay { get; set; }
        public Nullable<int> LSILUnOperater { get; set; }
        public Nullable<int> LSILUnbepaint { get; set; }
        public Nullable<int> LSILPartUnbepaint { get; set; }
        public Nullable<int> HSILIncrassatedCompact { get; set; }
        public Nullable<int> HSILBoundaryClear { get; set; }
        public Nullable<int> HSILCuffBodyGlandOpening { get; set; }
        public Nullable<int> HSILBulge { get; set; }
        public Nullable<int> HSILConfertusNipple { get; set; }
        public Nullable<int> HSILInsideBoundaryRemark { get; set; }
        public Nullable<int> HSILNone { get; set; }
        public Nullable<int> HSILCrudeInlay { get; set; }
        public Nullable<int> HSILCrudePunctiform { get; set; }
        public Nullable<int> HSILAbnormitydBlood { get; set; }
        public Nullable<int> HSILUnOperater { get; set; }
        public Nullable<int> HSILUnbepaint { get; set; }
        public Nullable<int> HSILPartUnbepaint { get; set; }
        public Nullable<int> IrregularSurface { get; set; }
        public Nullable<int> FragilityAtypiaBlood { get; set; }
        public Nullable<int> AbnormalSecretion { get; set; }
        public Nullable<int> Neoplasm { get; set; }
        public Nullable<int> ExogenicGoitre { get; set; }
        public Nullable<int> PregnancyBleeding { get; set; }
        public Nullable<int> UlcerNecrosis { get; set; }
        public Nullable<int> VingerCanceration { get; set; }
        public Nullable<int> LugolIodineStaining { get; set; }
        public Nullable<int> TrichomonasInfection { get; set; }
        public Nullable<int> Polyp { get; set; }
        public Nullable<int> CervicalMyoma { get; set; }
        public Nullable<int> ContactBleeding { get; set; }
        public Nullable<int> Erosion { get; set; }
        public Nullable<int> Leukoplakia { get; set; }
        public Nullable<int> EasyCrispOrganize { get; set; }
        public Nullable<int> TreatChange { get; set; }
        public Nullable<int> OtherInspect { get; set; }
        public string SatisfactionDegree { get; set; }
        public string DisagreementItem { get; set; }
        public string ConversionType { get; set; }
        public string Screen { get; set; }
        public string ScreenOther { get; set; }
        public string ReferralResult { get; set; }
        public string ReferralOther { get; set; }
        public Nullable<int> OverAllVinegarWhiteEpithelium { get; set; }
        public Nullable<int> OverAllInfection { get; set; }
        public string Attention { get; set; }
        public string DisposeSuggestion { get; set; }
        public Nullable<System.DateTime> FlupDate { get; set; }
        public string SelectedPicture { get; set; }
        public string Associated_Documents { get; set; }
        public string Code { get; set; }
        public string Full_Name { get; set; }
        public string Name { get; set; }
        public string Category_Code { get; set; }
        public string Category { get; set; }
        public Nullable<short> State_Code { get; set; }
        public string State { get; set; }
        public Nullable<int> Sort_Code { get; set; }
        public Nullable<short> Allow_Edit { get; set; }
        public Nullable<short> Allow_Delete { get; set; }
        public Nullable<short> Is_Visible { get; set; }
        public Nullable<short> Is_Public { get; set; }
        public Nullable<short> Enabled { get; set; }
        public Nullable<short> Deletion_State_Code { get; set; }
        public string Contents { get; set; }
        public string Description { get; set; }
        public string Tag { get; set; }
        public System.DateTime Create_On { get; set; }
        public string Create_User_Id { get; set; }
        public string Create_By { get; set; }
        public System.DateTime Modified_On { get; set; }
        public string Modified_User_Id { get; set; }
        public string Modified_By { get; set; }
        public string PathologyPlace { get; set; }
        public string PathologyLocal { get; set; }
        public string PathologyArea { get; set; }
        public string PathologySize { get; set; }
        public string BeforeUseEthylicacid { get; set; }
        public string AfterUseEthylicacid { get; set; }
    }
}
