//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _22_EntityFramework_DBFirst
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UserCenter : DbContext
    {
        public UserCenter()
            : base("name=UserCenter")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Base_Area> Base_Area { get; set; }
        public virtual DbSet<Base_Comment> Base_Comment { get; set; }
        public virtual DbSet<Base_Contact> Base_Contact { get; set; }
        public virtual DbSet<Base_Contact_Details> Base_Contact_Details { get; set; }
        public virtual DbSet<Base_Department> Base_Department { get; set; }
        public virtual DbSet<Base_Exception> Base_Exception { get; set; }
        public virtual DbSet<Base_File> Base_File { get; set; }
        public virtual DbSet<Base_Folder> Base_Folder { get; set; }
        public virtual DbSet<Base_Holidays> Base_Holidays { get; set; }
        public virtual DbSet<Base_Item_Details> Base_Item_Details { get; set; }
        public virtual DbSet<Base_Items> Base_Items { get; set; }
        public virtual DbSet<Base_Knowledge> Base_Knowledge { get; set; }
        public virtual DbSet<Base_Log> Base_Log { get; set; }
        public virtual DbSet<Base_Login_Log> Base_Login_Log { get; set; }
        public virtual DbSet<Base_Message> Base_Message { get; set; }
        public virtual DbSet<BASE_MESSAGE_RECENT> BASE_MESSAGE_RECENT { get; set; }
        public virtual DbSet<Base_Modify_Record> Base_Modify_Record { get; set; }
        public virtual DbSet<Base_News> Base_News { get; set; }
        public virtual DbSet<Base_Notice> Base_Notice { get; set; }
        public virtual DbSet<Base_Organize> Base_Organize { get; set; }
        public virtual DbSet<Base_Organize_Scope> Base_Organize_Scope { get; set; }
        public virtual DbSet<Base_Parameter> Base_Parameter { get; set; }
        public virtual DbSet<Base_Permission> Base_Permission { get; set; }
        public virtual DbSet<Base_Permission_Scope> Base_Permission_Scope { get; set; }
        public virtual DbSet<Base_Role> Base_Role { get; set; }
        public virtual DbSet<Base_Role_Organize> Base_Role_Organize { get; set; }
        public virtual DbSet<Base_Sequence> Base_Sequence { get; set; }
        public virtual DbSet<Base_Staff> Base_Staff { get; set; }
        public virtual DbSet<Base_Staff_Organize> Base_Staff_Organize { get; set; }
        public virtual DbSet<Base_System> Base_System { get; set; }
        public virtual DbSet<Base_Table_Columns> Base_Table_Columns { get; set; }
        public virtual DbSet<Base_User> Base_User { get; set; }
        public virtual DbSet<Base_User_Address> Base_User_Address { get; set; }
        public virtual DbSet<Base_User_Contact> Base_User_Contact { get; set; }
        public virtual DbSet<Base_User_Express> Base_User_Express { get; set; }
        public virtual DbSet<Base_User_Log_On> Base_User_Log_On { get; set; }
        public virtual DbSet<Base_User_Organize> Base_User_Organize { get; set; }
        public virtual DbSet<Base_User_Role> Base_User_Role { get; set; }
        public virtual DbSet<Base_User_Score> Base_User_Score { get; set; }
        public virtual DbSet<Business_Card> Business_Card { get; set; }
        public virtual DbSet<Colp_Appointment_Detail> Colp_Appointment_Detail { get; set; }
        public virtual DbSet<Colp_Audit_Diagnose_Detail> Colp_Audit_Diagnose_Detail { get; set; }
        public virtual DbSet<Colp_Biopsy_Detail> Colp_Biopsy_Detail { get; set; }
        public virtual DbSet<Colp_Biopsy_Report_Detail> Colp_Biopsy_Report_Detail { get; set; }
        public virtual DbSet<Colp_Check_List> Colp_Check_List { get; set; }
        public virtual DbSet<Colp_Check_Report_Detail> Colp_Check_Report_Detail { get; set; }
        public virtual DbSet<Colp_Configuration_List> Colp_Configuration_List { get; set; }
        public virtual DbSet<Colp_Data_Sync_Detail> Colp_Data_Sync_Detail { get; set; }
        public virtual DbSet<Colp_Diagnose_Detail> Colp_Diagnose_Detail { get; set; }
        public virtual DbSet<Colp_Diagnose_Report_Detail> Colp_Diagnose_Report_Detail { get; set; }
        public virtual DbSet<Colp_Equipment_List> Colp_Equipment_List { get; set; }
        public virtual DbSet<Colp_Evaluate_AI> Colp_Evaluate_AI { get; set; }
        public virtual DbSet<Colp_Evaluate_RCI_Detail> Colp_Evaluate_RCI_Detail { get; set; }
        public virtual DbSet<Colp_File_Detail> Colp_File_Detail { get; set; }
        public virtual DbSet<Colp_Flup_Detail> Colp_Flup_Detail { get; set; }
        public virtual DbSet<Colp_Instruments_List> Colp_Instruments_List { get; set; }
        public virtual DbSet<Colp_Operation_Detail> Colp_Operation_Detail { get; set; }
        public virtual DbSet<Colp_Operation_Report_Detail> Colp_Operation_Report_Detail { get; set; }
        public virtual DbSet<Colp_Pathology_Detail> Colp_Pathology_Detail { get; set; }
        public virtual DbSet<Colp_Patient_List> Colp_Patient_List { get; set; }
        public virtual DbSet<Colp_Picture_Annotate_Detail> Colp_Picture_Annotate_Detail { get; set; }
        public virtual DbSet<Colp_QueueManage_List> Colp_QueueManage_List { get; set; }
        public virtual DbSet<Colp_Report_List> Colp_Report_List { get; set; }
        public virtual DbSet<Colp_Report_Tempelate_Detail> Colp_Report_Tempelate_Detail { get; set; }
        public virtual DbSet<Colp_Report_Tempelate_List> Colp_Report_Tempelate_List { get; set; }
        public virtual DbSet<Colp_Statistical_List> Colp_Statistical_List { get; set; }
        public virtual DbSet<Colp_Term_Detailrrrr> Colp_Term_Detailrrrr { get; set; }
        public virtual DbSet<Colp_Typicalcase_Detail> Colp_Typicalcase_Detail { get; set; }
        public virtual DbSet<dtproperties> dtproperties { get; set; }
        public virtual DbSet<Items_Area> Items_Area { get; set; }
        public virtual DbSet<Items_Audit_Status> Items_Audit_Status { get; set; }
        public virtual DbSet<Items_Big_Area> Items_Big_Area { get; set; }
        public virtual DbSet<Items_Bug_Category> Items_Bug_Category { get; set; }
        public virtual DbSet<Items_Bug_Level> Items_Bug_Level { get; set; }
        public virtual DbSet<Items_Condition> Items_Condition { get; set; }
        public virtual DbSet<Items_Duty> Items_Duty { get; set; }
        public virtual DbSet<Items_EditFields> Items_EditFields { get; set; }
        public virtual DbSet<Items_Education> Items_Education { get; set; }
        public virtual DbSet<Items_Gender> Items_Gender { get; set; }
        public virtual DbSet<Items_Marriage> Items_Marriage { get; set; }
        public virtual DbSet<Items_Nationality> Items_Nationality { get; set; }
        public virtual DbSet<Items_News_Category> Items_News_Category { get; set; }
        public virtual DbSet<Items_Organize_Category> Items_Organize_Category { get; set; }
        public virtual DbSet<Items_Organize_Joining_Methods> Items_Organize_Joining_Methods { get; set; }
        public virtual DbSet<Items_Party> Items_Party { get; set; }
        public virtual DbSet<Items_Priority> Items_Priority { get; set; }
        public virtual DbSet<Items_Role_Category> Items_Role_Category { get; set; }
        public virtual DbSet<Items_Security_Level> Items_Security_Level { get; set; }
        public virtual DbSet<Items_System> Items_System { get; set; }
        public virtual DbSet<Items_Table_Permission_Scope> Items_Table_Permission_Scope { get; set; }
        public virtual DbSet<Items_Title> Items_Title { get; set; }
        public virtual DbSet<Items_True_False> Items_True_False { get; set; }
        public virtual DbSet<Items_Units> Items_Units { get; set; }
        public virtual DbSet<Items_Work_Status> Items_Work_Status { get; set; }
        public virtual DbSet<Items_Working_Property> Items_Working_Property { get; set; }
        public virtual DbSet<Items_Yes_No> Items_Yes_No { get; set; }
        public virtual DbSet<Mvc_Base_Items> Mvc_Base_Items { get; set; }
        public virtual DbSet<Mvc_Base_Module> Mvc_Base_Module { get; set; }
        public virtual DbSet<Mvc_Base_Organize_Scope> Mvc_Base_Organize_Scope { get; set; }
        public virtual DbSet<Mvc_Base_Permission> Mvc_Base_Permission { get; set; }
        public virtual DbSet<Mvc_Base_Permission_Scope> Mvc_Base_Permission_Scope { get; set; }
        public virtual DbSet<Mvc_Base_Role> Mvc_Base_Role { get; set; }
        public virtual DbSet<Mvc_Base_Role_Organize> Mvc_Base_Role_Organize { get; set; }
        public virtual DbSet<Mvc_Base_User_Role> Mvc_Base_User_Role { get; set; }
        public virtual DbSet<Option_Items_Computer_Category> Option_Items_Computer_Category { get; set; }
        public virtual DbSet<Option_Items_Disability> Option_Items_Disability { get; set; }
        public virtual DbSet<Option_Items_Express> Option_Items_Express { get; set; }
        public virtual DbSet<Option_Items_House_hold> Option_Items_House_hold { get; set; }
        public virtual DbSet<Option_Items_Post_Category> Option_Items_Post_Category { get; set; }
        public virtual DbSet<Option_Items_Salary_Item_Category> Option_Items_Salary_Item_Category { get; set; }
        public virtual DbSet<Option_Items_Send_Category> Option_Items_Send_Category { get; set; }
        public virtual DbSet<PDA_USER_LOG_ON> PDA_USER_LOG_ON { get; set; }
        public virtual DbSet<System_Parameter> System_Parameter { get; set; }
        public virtual DbSet<Base_Module> Base_Module { get; set; }
        public virtual DbSet<BASE_ORGANIZE_HORIZONTAL> BASE_ORGANIZE_HORIZONTAL { get; set; }
        public virtual DbSet<Base_Organize_Log> Base_Organize_Log { get; set; }
        public virtual DbSet<Base_User_Log> Base_User_Log { get; set; }
        public virtual DbSet<Colp_Term_Detail> Colp_Term_Detail { get; set; }
    }
}
