//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _22_EntityFramework_DBFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mvc_Base_Organize_Scope
    {
        public string ID { get; set; }
        public string RESOURCE_CATEGORY { get; set; }
        public string RESOURCE_ID { get; set; }
        public string PERMISSION_ID { get; set; }
        public Nullable<int> ALL_DATA { get; set; }
        public int USER_COMPANY { get; set; }
        public Nullable<int> USER_SUB_COMPANY { get; set; }
        public Nullable<int> USER_DEPARTMENT { get; set; }
        public Nullable<int> USER_SUB_DEPARTMENT { get; set; }
        public Nullable<int> USER_WORKGROUP { get; set; }
        public Nullable<int> ONLY_OWN_DATA { get; set; }
        public Nullable<int> NOT_ALLOWED { get; set; }
        public Nullable<int> BY_DETAILS { get; set; }
        public Nullable<int> CONTAIN_CHILD { get; set; }
        public Nullable<int> ENABLED { get; set; }
        public Nullable<int> DELETION_STATE_CODE { get; set; }
        public string DESCRIPTION { get; set; }
        public System.DateTime CREATE_ON { get; set; }
        public string CREATE_USER_ID { get; set; }
        public string CREATE_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_ON { get; set; }
        public string MODIFIED_USER_ID { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<int> PROVINCE { get; set; }
        public Nullable<int> CITY { get; set; }
        public Nullable<int> DISTRICT { get; set; }
        public Nullable<int> STREET { get; set; }
    }
}
