//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _22_EntityFramework_DBFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Option_Items_Post_Category
    {
        public int Id { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string ItemCode { get; set; }
        public string ItemName { get; set; }
        public string ItemValue { get; set; }
        public int Enabled { get; set; }
        public int AllowEdit { get; set; }
        public int AllowDelete { get; set; }
        public int IsPublic { get; set; }
        public int DeletionStateCode { get; set; }
        public Nullable<int> SortCode { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> Create_On { get; set; }
        public string Create_User_Id { get; set; }
        public string Create_By { get; set; }
        public Nullable<System.DateTime> Modified_On { get; set; }
        public string Modified_User_Id { get; set; }
        public string Modified_By { get; set; }
    }
}
