//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _22_EntityFramework_DBFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDA_USER_LOG_ON
    {
        public string ID { get; set; }
        public string USER_FROM { get; set; }
        public string USER_PASSWORD { get; set; }
        public string OPEN_ID { get; set; }
        public Nullable<System.DateTime> ALLOW_START_TIME { get; set; }
        public Nullable<System.DateTime> ALLOW_END_TIME { get; set; }
        public Nullable<System.DateTime> LOCK_START_DATE { get; set; }
        public Nullable<System.DateTime> LOCK_END_DATE { get; set; }
        public Nullable<System.DateTime> FIRST_VISIT { get; set; }
        public Nullable<System.DateTime> PREVIOUS_VISIT { get; set; }
        public Nullable<System.DateTime> LAST_VISIT { get; set; }
        public Nullable<int> LOG_ON_COUNT { get; set; }
        public Nullable<int> PASSWORD_ERROR_COUNT { get; set; }
        public Nullable<System.DateTime> CHANGE_PASSWORD_DATE { get; set; }
        public Nullable<int> IS_STAFF { get; set; }
        public Nullable<int> USER_ON_LINE { get; set; }
        public Nullable<int> MULTI_USER_LOGIN { get; set; }
        public Nullable<int> SHOW_COUNT { get; set; }
        public Nullable<int> IS_VISIBLE { get; set; }
        public Nullable<int> CHECK_IPADDRESS { get; set; }
        public string VERIFICATION_CODE { get; set; }
        public string IPADDRESS { get; set; }
        public string MAC_ADDRESS { get; set; }
        public string QUESTION { get; set; }
        public string ANSWER_QUESTION { get; set; }
        public int ENABLED { get; set; }
        public Nullable<int> DELETION_STATE_CODE { get; set; }
        public Nullable<int> SORT_CODE { get; set; }
        public string DESCRIPTION { get; set; }
        public System.DateTime CREATE_ON { get; set; }
        public string CREATE_USER_ID { get; set; }
        public string CREATE_BY { get; set; }
        public System.DateTime MODIFIED_ON { get; set; }
        public string MODIFIED_USER_ID { get; set; }
        public string MODIFIED_BY { get; set; }
        public string SALT { get; set; }
        public Nullable<System.DateTime> OPEN_ID_TIMEOUT { get; set; }
        public string SYSTEM_CODE { get; set; }
        public string IPADDRESS_NAME { get; set; }
        public Nullable<int> PASSWORD_STRENGTH { get; set; }
        public string COMPUTER_NAME { get; set; }
        public Nullable<int> NEED_MODIFY_PASSWORD { get; set; }
        public string COMPANY_ID { get; set; }
        public string COMPANY { get; set; }
        public Nullable<int> CHECK_MAC_ADDRESS { get; set; }
    }
}
