//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _19_soa.WebServiceTest01 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WebServiceTest01.WebServiceTest01Soap")]
    public interface WebServiceTest01Soap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 HelloWorldResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        _19_soa.WebServiceTest01.HelloWorldResponse HelloWorld(_19_soa.WebServiceTest01.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<_19_soa.WebServiceTest01.HelloWorldResponse> HelloWorldAsync(_19_soa.WebServiceTest01.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Sum", ReplyAction="*")]
        int Sum(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Sum", ReplyAction="*")]
        System.Threading.Tasks.Task<int> SumAsync(int a, int b);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 GetUserByIdResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserById", ReplyAction="*")]
        _19_soa.WebServiceTest01.GetUserByIdResponse GetUserById(_19_soa.WebServiceTest01.GetUserByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserById", ReplyAction="*")]
        System.Threading.Tasks.Task<_19_soa.WebServiceTest01.GetUserByIdResponse> GetUserByIdAsync(_19_soa.WebServiceTest01.GetUserByIdRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public _19_soa.WebServiceTest01.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(_19_soa.WebServiceTest01.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public _19_soa.WebServiceTest01.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(_19_soa.WebServiceTest01.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserById", Namespace="http://tempuri.org/", Order=0)]
        public _19_soa.WebServiceTest01.GetUserByIdRequestBody Body;
        
        public GetUserByIdRequest() {
        }
        
        public GetUserByIdRequest(_19_soa.WebServiceTest01.GetUserByIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserByIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public GetUserByIdRequestBody() {
        }
        
        public GetUserByIdRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserByIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public _19_soa.WebServiceTest01.GetUserByIdResponseBody Body;
        
        public GetUserByIdResponse() {
        }
        
        public GetUserByIdResponse(_19_soa.WebServiceTest01.GetUserByIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserByIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetUserByIdResult;
        
        public GetUserByIdResponseBody() {
        }
        
        public GetUserByIdResponseBody(string GetUserByIdResult) {
            this.GetUserByIdResult = GetUserByIdResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceTest01SoapChannel : _19_soa.WebServiceTest01.WebServiceTest01Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceTest01SoapClient : System.ServiceModel.ClientBase<_19_soa.WebServiceTest01.WebServiceTest01Soap>, _19_soa.WebServiceTest01.WebServiceTest01Soap {
        
        public WebServiceTest01SoapClient() {
        }
        
        public WebServiceTest01SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceTest01SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceTest01SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceTest01SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _19_soa.WebServiceTest01.HelloWorldResponse _19_soa.WebServiceTest01.WebServiceTest01Soap.HelloWorld(_19_soa.WebServiceTest01.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            _19_soa.WebServiceTest01.HelloWorldRequest inValue = new _19_soa.WebServiceTest01.HelloWorldRequest();
            inValue.Body = new _19_soa.WebServiceTest01.HelloWorldRequestBody();
            _19_soa.WebServiceTest01.HelloWorldResponse retVal = ((_19_soa.WebServiceTest01.WebServiceTest01Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<_19_soa.WebServiceTest01.HelloWorldResponse> _19_soa.WebServiceTest01.WebServiceTest01Soap.HelloWorldAsync(_19_soa.WebServiceTest01.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<_19_soa.WebServiceTest01.HelloWorldResponse> HelloWorldAsync() {
            _19_soa.WebServiceTest01.HelloWorldRequest inValue = new _19_soa.WebServiceTest01.HelloWorldRequest();
            inValue.Body = new _19_soa.WebServiceTest01.HelloWorldRequestBody();
            return ((_19_soa.WebServiceTest01.WebServiceTest01Soap)(this)).HelloWorldAsync(inValue);
        }
        
        public int Sum(int a, int b) {
            return base.Channel.Sum(a, b);
        }
        
        public System.Threading.Tasks.Task<int> SumAsync(int a, int b) {
            return base.Channel.SumAsync(a, b);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _19_soa.WebServiceTest01.GetUserByIdResponse _19_soa.WebServiceTest01.WebServiceTest01Soap.GetUserById(_19_soa.WebServiceTest01.GetUserByIdRequest request) {
            return base.Channel.GetUserById(request);
        }
        
        public string GetUserById(int id) {
            _19_soa.WebServiceTest01.GetUserByIdRequest inValue = new _19_soa.WebServiceTest01.GetUserByIdRequest();
            inValue.Body = new _19_soa.WebServiceTest01.GetUserByIdRequestBody();
            inValue.Body.id = id;
            _19_soa.WebServiceTest01.GetUserByIdResponse retVal = ((_19_soa.WebServiceTest01.WebServiceTest01Soap)(this)).GetUserById(inValue);
            return retVal.Body.GetUserByIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<_19_soa.WebServiceTest01.GetUserByIdResponse> _19_soa.WebServiceTest01.WebServiceTest01Soap.GetUserByIdAsync(_19_soa.WebServiceTest01.GetUserByIdRequest request) {
            return base.Channel.GetUserByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<_19_soa.WebServiceTest01.GetUserByIdResponse> GetUserByIdAsync(int id) {
            _19_soa.WebServiceTest01.GetUserByIdRequest inValue = new _19_soa.WebServiceTest01.GetUserByIdRequest();
            inValue.Body = new _19_soa.WebServiceTest01.GetUserByIdRequestBody();
            inValue.Body.id = id;
            return ((_19_soa.WebServiceTest01.WebServiceTest01Soap)(this)).GetUserByIdAsync(inValue);
        }
    }
}
