//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _19_UnitTestWebService.WebServiceTest01 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WebServiceTest01.WebServiceTest01Soap")]
    public interface WebServiceTest01Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<string> HelloWorldAsync();
        
        // CODEGEN: 消息 SumRequest 以后生成的消息协定具有标头
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Sum", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        _19_UnitTestWebService.WebServiceTest01.SumResponse Sum(_19_UnitTestWebService.WebServiceTest01.SumRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Sum", ReplyAction="*")]
        System.Threading.Tasks.Task<_19_UnitTestWebService.WebServiceTest01.SumResponse> SumAsync(_19_UnitTestWebService.WebServiceTest01.SumRequest request);
        
        // CODEGEN: 消息 GetUserByIdRequest 以后生成的消息协定具有标头
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserById", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        _19_UnitTestWebService.WebServiceTest01.GetUserByIdResponse GetUserById(_19_UnitTestWebService.WebServiceTest01.GetUserByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserById", ReplyAction="*")]
        System.Threading.Tasks.Task<_19_UnitTestWebService.WebServiceTest01.GetUserByIdResponse> GetUserByIdAsync(_19_UnitTestWebService.WebServiceTest01.GetUserByIdRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CustomSoapHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string userNameField;
        
        private string passWordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("UserName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string PassWord {
            get {
                return this.passWordField;
            }
            set {
                this.passWordField = value;
                this.RaisePropertyChanged("PassWord");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Sum", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SumRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public _19_UnitTestWebService.WebServiceTest01.CustomSoapHeader CustomSoapHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int a;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int b;
        
        public SumRequest() {
        }
        
        public SumRequest(_19_UnitTestWebService.WebServiceTest01.CustomSoapHeader CustomSoapHeader, int a, int b) {
            this.CustomSoapHeader = CustomSoapHeader;
            this.a = a;
            this.b = b;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SumResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SumResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int SumResult;
        
        public SumResponse() {
        }
        
        public SumResponse(int SumResult) {
            this.SumResult = SumResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetUserById", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetUserByIdRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public _19_UnitTestWebService.WebServiceTest01.CustomSoapHeader CustomSoapHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int id;
        
        public GetUserByIdRequest() {
        }
        
        public GetUserByIdRequest(_19_UnitTestWebService.WebServiceTest01.CustomSoapHeader CustomSoapHeader, int id) {
            this.CustomSoapHeader = CustomSoapHeader;
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetUserByIdResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetUserByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string GetUserByIdResult;
        
        public GetUserByIdResponse() {
        }
        
        public GetUserByIdResponse(string GetUserByIdResult) {
            this.GetUserByIdResult = GetUserByIdResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceTest01SoapChannel : _19_UnitTestWebService.WebServiceTest01.WebServiceTest01Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceTest01SoapClient : System.ServiceModel.ClientBase<_19_UnitTestWebService.WebServiceTest01.WebServiceTest01Soap>, _19_UnitTestWebService.WebServiceTest01.WebServiceTest01Soap {
        
        public WebServiceTest01SoapClient() {
        }
        
        public WebServiceTest01SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceTest01SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceTest01SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceTest01SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public System.Threading.Tasks.Task<string> HelloWorldAsync() {
            return base.Channel.HelloWorldAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _19_UnitTestWebService.WebServiceTest01.SumResponse _19_UnitTestWebService.WebServiceTest01.WebServiceTest01Soap.Sum(_19_UnitTestWebService.WebServiceTest01.SumRequest request) {
            return base.Channel.Sum(request);
        }
        
        public int Sum(_19_UnitTestWebService.WebServiceTest01.CustomSoapHeader CustomSoapHeader, int a, int b) {
            _19_UnitTestWebService.WebServiceTest01.SumRequest inValue = new _19_UnitTestWebService.WebServiceTest01.SumRequest();
            inValue.CustomSoapHeader = CustomSoapHeader;
            inValue.a = a;
            inValue.b = b;
            _19_UnitTestWebService.WebServiceTest01.SumResponse retVal = ((_19_UnitTestWebService.WebServiceTest01.WebServiceTest01Soap)(this)).Sum(inValue);
            return retVal.SumResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<_19_UnitTestWebService.WebServiceTest01.SumResponse> _19_UnitTestWebService.WebServiceTest01.WebServiceTest01Soap.SumAsync(_19_UnitTestWebService.WebServiceTest01.SumRequest request) {
            return base.Channel.SumAsync(request);
        }
        
        public System.Threading.Tasks.Task<_19_UnitTestWebService.WebServiceTest01.SumResponse> SumAsync(_19_UnitTestWebService.WebServiceTest01.CustomSoapHeader CustomSoapHeader, int a, int b) {
            _19_UnitTestWebService.WebServiceTest01.SumRequest inValue = new _19_UnitTestWebService.WebServiceTest01.SumRequest();
            inValue.CustomSoapHeader = CustomSoapHeader;
            inValue.a = a;
            inValue.b = b;
            return ((_19_UnitTestWebService.WebServiceTest01.WebServiceTest01Soap)(this)).SumAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _19_UnitTestWebService.WebServiceTest01.GetUserByIdResponse _19_UnitTestWebService.WebServiceTest01.WebServiceTest01Soap.GetUserById(_19_UnitTestWebService.WebServiceTest01.GetUserByIdRequest request) {
            return base.Channel.GetUserById(request);
        }
        
        public string GetUserById(_19_UnitTestWebService.WebServiceTest01.CustomSoapHeader CustomSoapHeader, int id) {
            _19_UnitTestWebService.WebServiceTest01.GetUserByIdRequest inValue = new _19_UnitTestWebService.WebServiceTest01.GetUserByIdRequest();
            inValue.CustomSoapHeader = CustomSoapHeader;
            inValue.id = id;
            _19_UnitTestWebService.WebServiceTest01.GetUserByIdResponse retVal = ((_19_UnitTestWebService.WebServiceTest01.WebServiceTest01Soap)(this)).GetUserById(inValue);
            return retVal.GetUserByIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<_19_UnitTestWebService.WebServiceTest01.GetUserByIdResponse> _19_UnitTestWebService.WebServiceTest01.WebServiceTest01Soap.GetUserByIdAsync(_19_UnitTestWebService.WebServiceTest01.GetUserByIdRequest request) {
            return base.Channel.GetUserByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<_19_UnitTestWebService.WebServiceTest01.GetUserByIdResponse> GetUserByIdAsync(_19_UnitTestWebService.WebServiceTest01.CustomSoapHeader CustomSoapHeader, int id) {
            _19_UnitTestWebService.WebServiceTest01.GetUserByIdRequest inValue = new _19_UnitTestWebService.WebServiceTest01.GetUserByIdRequest();
            inValue.CustomSoapHeader = CustomSoapHeader;
            inValue.id = id;
            return ((_19_UnitTestWebService.WebServiceTest01.WebServiceTest01Soap)(this)).GetUserByIdAsync(inValue);
        }
    }
}
